---
name: Lint and Test Charts

on: [push, workflow_dispatch]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and Test Charts
        uses: IMIO/gha/helm-test-notify@v4
        with:
          HELM_RELEASE: plone
          HELM_NAMESPACE: plone
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
